
# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# in the templates available like {{ site.myvariable }}.
title: About Zachary Sang
email: zacharysang@gmail.com
headline: Zachary Sang
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://zacharysang.me" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
include: [_markdown/]

# Account ids
#snapwidget: 247552

# Contacts
phone: +1-513-808-7865

# Tracking
#googleAnalitycsID: UA-83933844-1

